server:
  port: 8088

#spring:
#  application:
#    name: nufront-web
#  datasource:
#    url: jdbc:mysql://localhost:3306/nufront-nt
#    username: root
#    password: 123456
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10


#nt:
#  columns: "id, mac, eau_mac, cm_sta_dir, over_hotime, hotime, suggestTa, suggestRssi, suggestDescribe"